[2024-11-18 23:58:23,747] - [    INFO] - [uvicorn.error] - [b23c2f58-e973-4d5c-81f7-890908338ba1] - Started server process [65003] - - [uvicorn/server.py:82]
[2024-11-18 23:58:23,747] - [    INFO] - [uvicorn.error] - [b23c2f58-e973-4d5c-81f7-890908338ba1] - Waiting for application startup. - - [lifespan/on.py:48]
[2024-11-18 23:58:23,748] - [    INFO] - [uvicorn.error] - [b23c2f58-e973-4d5c-81f7-890908338ba1] - Application startup complete. - - [lifespan/on.py:62]
[2024-11-18 23:58:25,466] - [    INFO] - [uvicorn.error] - [b23c2f58-e973-4d5c-81f7-890908338ba1] - Shutting down - - [uvicorn/server.py:262]
[2024-11-18 23:58:25,567] - [    INFO] - [uvicorn.error] - [b23c2f58-e973-4d5c-81f7-890908338ba1] - Waiting for application shutdown. - - [lifespan/on.py:67]
[2024-11-18 23:58:25,568] - [    INFO] - [uvicorn.error] - [b23c2f58-e973-4d5c-81f7-890908338ba1] - Application shutdown complete. - - [lifespan/on.py:76]
[2024-11-18 23:58:25,568] - [    INFO] - [uvicorn.error] - [b23c2f58-e973-4d5c-81f7-890908338ba1] - Finished server process [65003] - - [uvicorn/server.py:92]
[2024-11-18 23:58:27,208] - [    INFO] - [uvicorn.error] - [1227bf21-d620-4ec6-94b5-13a8c155aaec] - Started server process [65013] - - [uvicorn/server.py:82]
[2024-11-18 23:58:27,208] - [    INFO] - [uvicorn.error] - [1227bf21-d620-4ec6-94b5-13a8c155aaec] - Waiting for application startup. - - [lifespan/on.py:48]
[2024-11-18 23:58:27,209] - [    INFO] - [uvicorn.error] - [1227bf21-d620-4ec6-94b5-13a8c155aaec] - Application startup complete. - - [lifespan/on.py:62]
[2024-11-18 23:58:30,292] - [    INFO] - [   root] - [HobC_ZNL6D4IrtSTHf4rKg] - GET / 200 OK - - [core/middlewares.py:118]
[2024-11-18 23:58:31,057] - [ WARNING] - [   root] - [kRH-Ai60B5lhwF_d_H3RSw] - GET /favicon.ico 404 Not Found - - [core/middlewares.py:118]
[2024-11-18 23:58:33,587] - [    INFO] - [   root] - [8EgcUzrhxwp2o7-P2TYTNA] - GET /docs 200 OK - - [core/middlewares.py:118]
[2024-11-18 23:58:34,145] - [    INFO] - [   root] - [CduX3zSqumIxECMvWG-1TA] - GET /openapi.json 200 OK - - [core/middlewares.py:118]
[2024-11-18 23:59:12,491] - [    INFO] - [uvicorn.error] - [1227bf21-d620-4ec6-94b5-13a8c155aaec] - Shutting down - - [uvicorn/server.py:262]
[2024-11-18 23:59:12,593] - [    INFO] - [uvicorn.error] - [1227bf21-d620-4ec6-94b5-13a8c155aaec] - Waiting for application shutdown. - - [lifespan/on.py:67]
[2024-11-18 23:59:12,594] - [    INFO] - [uvicorn.error] - [1227bf21-d620-4ec6-94b5-13a8c155aaec] - Application shutdown complete. - - [lifespan/on.py:76]
[2024-11-18 23:59:12,594] - [    INFO] - [uvicorn.error] - [1227bf21-d620-4ec6-94b5-13a8c155aaec] - Finished server process [65013] - - [uvicorn/server.py:92]
[2024-11-19 00:00:16,834] - [    INFO] - [uvicorn.error] - [8053b698-8edb-47ee-9cb3-bd0201fb5d90] - Started server process [65134] - - [uvicorn/server.py:82]
[2024-11-19 00:00:16,835] - [    INFO] - [uvicorn.error] - [8053b698-8edb-47ee-9cb3-bd0201fb5d90] - Waiting for application startup. - - [lifespan/on.py:48]
[2024-11-19 00:00:16,836] - [    INFO] - [uvicorn.error] - [8053b698-8edb-47ee-9cb3-bd0201fb5d90] - Application startup complete. - - [lifespan/on.py:62]
[2024-11-19 00:00:19,183] - [    INFO] - [   root] - [V3BkAwoPix7W38Ldg2Ymxg] - GET /docs 200 OK - - [core/middlewares.py:118]
[2024-11-19 00:00:20,060] - [    INFO] - [   root] - [fgcuczWwjdErBmiNknOFWA] - GET /openapi.json 200 OK - - [core/middlewares.py:118]
[2024-11-19 00:00:30,273] - [   DEBUG] - [   root] - [rKvLAiSbhx7aA-59fMkRIA] - /account request query: {"limit": "100"} - - [core/middlewares.py:160]
[2024-11-19 00:00:30,283] - [   ERROR] - [   root] - [rKvLAiSbhx7aA-59fMkRIA] - Error in middleware: 'Provide' object has no attribute 'get_accounts'. Full traceback: Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 111, in receive
    return self.receive_nowait()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 124, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 157, in call_next
    message = await recv_stream.receive()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Documents/TONQuests/TONQuest/server/core/middlewares.py", line 49, in catch_exceptions_middleware
    return await call_next(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/dependency_injector/wiring.py", line 994, in _patched
    return await _async_inject(
  File "src/dependency_injector/_cwiring.pyx", line 66, in _async_inject
  File "/Users/creator/Documents/TONQuests/TONQuest/server/apps/account/router.py", line 29, in get_accounts
    return await account_service.get_accounts(limit)
AttributeError: 'Provide' object has no attribute 'get_accounts'
 - - [core/middlewares.py:96]
[2024-11-19 00:00:30,295] - [   ERROR] - [   root] - [rKvLAiSbhx7aA-59fMkRIA] - GET /account?limit=100 500 Internal Server Error - - [core/middlewares.py:118]
[2024-11-19 00:00:52,836] - [    INFO] - [uvicorn.error] - [8053b698-8edb-47ee-9cb3-bd0201fb5d90] - Shutting down - - [uvicorn/server.py:262]
[2024-11-19 00:00:52,938] - [    INFO] - [uvicorn.error] - [8053b698-8edb-47ee-9cb3-bd0201fb5d90] - Waiting for application shutdown. - - [lifespan/on.py:67]
[2024-11-19 00:00:52,940] - [    INFO] - [uvicorn.error] - [8053b698-8edb-47ee-9cb3-bd0201fb5d90] - Application shutdown complete. - - [lifespan/on.py:76]
[2024-11-19 00:00:52,940] - [    INFO] - [uvicorn.error] - [8053b698-8edb-47ee-9cb3-bd0201fb5d90] - Finished server process [65134] - - [uvicorn/server.py:92]
[2024-11-19 00:00:53,565] - [    INFO] - [uvicorn.error] - [48130430-941c-484d-9869-6dfc3ce4a305] - Started server process [65164] - - [uvicorn/server.py:82]
[2024-11-19 00:00:53,565] - [    INFO] - [uvicorn.error] - [48130430-941c-484d-9869-6dfc3ce4a305] - Waiting for application startup. - - [lifespan/on.py:48]
[2024-11-19 00:00:53,566] - [    INFO] - [uvicorn.error] - [48130430-941c-484d-9869-6dfc3ce4a305] - Application startup complete. - - [lifespan/on.py:62]
[2024-11-19 00:00:55,838] - [   DEBUG] - [   root] - [LPiT3t1IN9znHqVXl1P_Fg] - /account request query: {"limit": "100"} - - [core/middlewares.py:160]
[2024-11-19 00:00:55,844] - [   ERROR] - [   root] - [LPiT3t1IN9znHqVXl1P_Fg] - Error in middleware: 'Provide' object has no attribute 'get_accounts'. Full traceback: Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 111, in receive
    return self.receive_nowait()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 124, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 157, in call_next
    message = await recv_stream.receive()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Documents/TONQuests/TONQuest/server/core/middlewares.py", line 49, in catch_exceptions_middleware
    return await call_next(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/dependency_injector/wiring.py", line 994, in _patched
    return await _async_inject(
  File "src/dependency_injector/_cwiring.pyx", line 66, in _async_inject
  File "/Users/creator/Documents/TONQuests/TONQuest/server/apps/account/router.py", line 29, in get_accounts
    return await account_service.get_accounts(limit)
AttributeError: 'Provide' object has no attribute 'get_accounts'
 - - [core/middlewares.py:96]
[2024-11-19 00:00:55,848] - [   ERROR] - [   root] - [LPiT3t1IN9znHqVXl1P_Fg] - GET /account?limit=100 500 Internal Server Error - - [core/middlewares.py:118]
[2024-11-19 00:03:43,171] - [    INFO] - [uvicorn.error] - [48130430-941c-484d-9869-6dfc3ce4a305] - Shutting down - - [uvicorn/server.py:262]
[2024-11-19 00:03:43,273] - [    INFO] - [uvicorn.error] - [48130430-941c-484d-9869-6dfc3ce4a305] - Waiting for application shutdown. - - [lifespan/on.py:67]
[2024-11-19 00:03:43,274] - [    INFO] - [uvicorn.error] - [48130430-941c-484d-9869-6dfc3ce4a305] - Application shutdown complete. - - [lifespan/on.py:76]
[2024-11-19 00:03:43,274] - [    INFO] - [uvicorn.error] - [48130430-941c-484d-9869-6dfc3ce4a305] - Finished server process [65164] - - [uvicorn/server.py:92]
[2024-11-19 00:03:43,906] - [    INFO] - [uvicorn.error] - [c0ca208d-c1be-44b2-9e41-c4e3a5cdde6d] - Started server process [65243] - - [uvicorn/server.py:82]
[2024-11-19 00:03:43,906] - [    INFO] - [uvicorn.error] - [c0ca208d-c1be-44b2-9e41-c4e3a5cdde6d] - Waiting for application startup. - - [lifespan/on.py:48]
[2024-11-19 00:03:43,908] - [    INFO] - [uvicorn.error] - [c0ca208d-c1be-44b2-9e41-c4e3a5cdde6d] - Application startup complete. - - [lifespan/on.py:62]
[2024-11-19 00:03:45,889] - [   DEBUG] - [   root] - [sZ0iUWux_8I0JCigpEcnOQ] - /account request query: {"limit": "100"} - - [core/middlewares.py:160]
[2024-11-19 00:03:45,909] - [   ERROR] - [   root] - [sZ0iUWux_8I0JCigpEcnOQ] - Error in middleware: 'Provide' object has no attribute 'get_accounts'. Full traceback: Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 111, in receive
    return self.receive_nowait()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 124, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 157, in call_next
    message = await recv_stream.receive()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Documents/TONQuests/TONQuest/server/core/middlewares.py", line 49, in catch_exceptions_middleware
    return await call_next(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/dependency_injector/wiring.py", line 994, in _patched
    return await _async_inject(
  File "src/dependency_injector/_cwiring.pyx", line 66, in _async_inject
  File "/Users/creator/Documents/TONQuests/TONQuest/server/apps/account/router.py", line 29, in get_accounts
    return await account_service.get_accounts(limit)
AttributeError: 'Provide' object has no attribute 'get_accounts'
 - - [core/middlewares.py:96]
[2024-11-19 00:03:45,911] - [   ERROR] - [   root] - [sZ0iUWux_8I0JCigpEcnOQ] - GET /account?limit=100 500 Internal Server Error - - [core/middlewares.py:118]
[2024-11-19 00:04:30,891] - [    INFO] - [uvicorn.error] - [c0ca208d-c1be-44b2-9e41-c4e3a5cdde6d] - Shutting down - - [uvicorn/server.py:262]
[2024-11-19 00:04:30,994] - [    INFO] - [uvicorn.error] - [c0ca208d-c1be-44b2-9e41-c4e3a5cdde6d] - Waiting for application shutdown. - - [lifespan/on.py:67]
[2024-11-19 00:04:30,995] - [    INFO] - [uvicorn.error] - [c0ca208d-c1be-44b2-9e41-c4e3a5cdde6d] - Application shutdown complete. - - [lifespan/on.py:76]
[2024-11-19 00:04:30,995] - [    INFO] - [uvicorn.error] - [c0ca208d-c1be-44b2-9e41-c4e3a5cdde6d] - Finished server process [65243] - - [uvicorn/server.py:92]
[2024-11-19 00:04:31,587] - [    INFO] - [uvicorn.error] - [4a64e50c-26a5-46ba-8558-7fd6fa2bc0d0] - Started server process [65279] - - [uvicorn/server.py:82]
[2024-11-19 00:04:31,587] - [    INFO] - [uvicorn.error] - [4a64e50c-26a5-46ba-8558-7fd6fa2bc0d0] - Waiting for application startup. - - [lifespan/on.py:48]
[2024-11-19 00:04:31,589] - [    INFO] - [uvicorn.error] - [4a64e50c-26a5-46ba-8558-7fd6fa2bc0d0] - Application startup complete. - - [lifespan/on.py:62]
[2024-11-19 00:04:34,168] - [   DEBUG] - [   root] - [zU1yGU0Xb782uHWfGVbuZg] - /account request query: {"limit": "100"} - - [core/middlewares.py:160]
[2024-11-19 00:04:34,188] - [   ERROR] - [   root] - [zU1yGU0Xb782uHWfGVbuZg] - Error in middleware: 'Provide' object has no attribute 'get_accounts'. Full traceback: Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 111, in receive
    return self.receive_nowait()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 124, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 157, in call_next
    message = await recv_stream.receive()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Documents/TONQuests/TONQuest/server/core/middlewares.py", line 49, in catch_exceptions_middleware
    return await call_next(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/dependency_injector/wiring.py", line 994, in _patched
    return await _async_inject(
  File "src/dependency_injector/_cwiring.pyx", line 66, in _async_inject
  File "/Users/creator/Documents/TONQuests/TONQuest/server/apps/account/router.py", line 30, in get_accounts
    return await account_service.get_accounts(limit)
AttributeError: 'Provide' object has no attribute 'get_accounts'
 - - [core/middlewares.py:96]
[2024-11-19 00:04:34,197] - [   ERROR] - [   root] - [zU1yGU0Xb782uHWfGVbuZg] - GET /account?limit=100 500 Internal Server Error - - [core/middlewares.py:118]
[2024-11-19 00:05:00,382] - [    INFO] - [uvicorn.error] - [4a64e50c-26a5-46ba-8558-7fd6fa2bc0d0] - Shutting down - - [uvicorn/server.py:262]
[2024-11-19 00:05:00,495] - [    INFO] - [uvicorn.error] - [4a64e50c-26a5-46ba-8558-7fd6fa2bc0d0] - Waiting for application shutdown. - - [lifespan/on.py:67]
[2024-11-19 00:05:00,505] - [    INFO] - [uvicorn.error] - [4a64e50c-26a5-46ba-8558-7fd6fa2bc0d0] - Application shutdown complete. - - [lifespan/on.py:76]
[2024-11-19 00:05:00,506] - [    INFO] - [uvicorn.error] - [4a64e50c-26a5-46ba-8558-7fd6fa2bc0d0] - Finished server process [65279] - - [uvicorn/server.py:92]
[2024-11-19 00:05:59,530] - [    INFO] - [uvicorn.error] - [8c8d7b3a-ab8d-4855-8e33-4b188e4177c0] - Started server process [65365] - - [uvicorn/server.py:82]
[2024-11-19 00:05:59,530] - [    INFO] - [uvicorn.error] - [8c8d7b3a-ab8d-4855-8e33-4b188e4177c0] - Waiting for application startup. - - [lifespan/on.py:48]
[2024-11-19 00:05:59,531] - [    INFO] - [uvicorn.error] - [8c8d7b3a-ab8d-4855-8e33-4b188e4177c0] - Application startup complete. - - [lifespan/on.py:62]
[2024-11-19 00:06:21,219] - [   DEBUG] - [   root] - [aPUX8CbHh8F4iKcE_iqCmQ] - /account request query: {"limit": "100"} - - [core/middlewares.py:160]
[2024-11-19 00:06:21,225] - [   ERROR] - [   root] - [aPUX8CbHh8F4iKcE_iqCmQ] - Error in middleware: 'Provide' object has no attribute 'get_accounts'. Full traceback: Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 111, in receive
    return self.receive_nowait()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 124, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 157, in call_next
    message = await recv_stream.receive()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Documents/TONQuests/TONQuest/server/core/middlewares.py", line 49, in catch_exceptions_middleware
    return await call_next(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/dependency_injector/wiring.py", line 994, in _patched
    return await _async_inject(
  File "src/dependency_injector/_cwiring.pyx", line 66, in _async_inject
  File "/Users/creator/Documents/TONQuests/TONQuest/server/apps/account/router.py", line 29, in get_accounts
    return await account_service.get_accounts(limit)
AttributeError: 'Provide' object has no attribute 'get_accounts'
 - - [core/middlewares.py:96]
[2024-11-19 00:06:21,238] - [   ERROR] - [   root] - [aPUX8CbHh8F4iKcE_iqCmQ] - GET /account?limit=100 500 Internal Server Error - - [core/middlewares.py:118]
[2024-11-19 00:06:50,769] - [    INFO] - [uvicorn.error] - [8c8d7b3a-ab8d-4855-8e33-4b188e4177c0] - Shutting down - - [uvicorn/server.py:262]
[2024-11-19 00:06:50,871] - [    INFO] - [uvicorn.error] - [8c8d7b3a-ab8d-4855-8e33-4b188e4177c0] - Waiting for application shutdown. - - [lifespan/on.py:67]
[2024-11-19 00:06:50,872] - [    INFO] - [uvicorn.error] - [8c8d7b3a-ab8d-4855-8e33-4b188e4177c0] - Application shutdown complete. - - [lifespan/on.py:76]
[2024-11-19 00:06:50,873] - [    INFO] - [uvicorn.error] - [8c8d7b3a-ab8d-4855-8e33-4b188e4177c0] - Finished server process [65365] - - [uvicorn/server.py:92]
[2024-11-19 00:07:08,761] - [    INFO] - [uvicorn.error] - [e2c1c1a6-b25e-4434-b771-c2f2192bdde9] - Started server process [65418] - - [uvicorn/server.py:82]
[2024-11-19 00:07:08,761] - [    INFO] - [uvicorn.error] - [e2c1c1a6-b25e-4434-b771-c2f2192bdde9] - Waiting for application startup. - - [lifespan/on.py:48]
[2024-11-19 00:07:08,763] - [    INFO] - [uvicorn.error] - [e2c1c1a6-b25e-4434-b771-c2f2192bdde9] - Application startup complete. - - [lifespan/on.py:62]
[2024-11-19 00:07:11,065] - [   DEBUG] - [   root] - [XzouquZwKCtD484LE0AbUg] - /account request query: {"limit": "100"} - - [core/middlewares.py:160]
[2024-11-19 00:07:11,213] - [   ERROR] - [   root] - [XzouquZwKCtD484LE0AbUg] - Error in middleware: 1 validation error for AccountSchema
is_trackable
  Field required [type=missing, input_value={'_id': '672f86cbcb7bcec7...e': 10}, 'out_msgs': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing. Full traceback: Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 111, in receive
    return self.receive_nowait()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 124, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 157, in call_next
    message = await recv_stream.receive()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Documents/TONQuests/TONQuest/server/core/middlewares.py", line 49, in catch_exceptions_middleware
    return await call_next(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/dependency_injector/wiring.py", line 994, in _patched
    return await _async_inject(
  File "src/dependency_injector/_cwiring.pyx", line 66, in _async_inject
  File "/Users/creator/Documents/TONQuests/TONQuest/server/apps/account/router.py", line 29, in get_accounts
    return await account_service.get_accounts(limit)
  File "/Users/creator/Documents/TONQuests/TONQuest/server/apps/account/service.py", line 57, in get_accounts
    return [AccountSchema(**item) for item in result[:limit]]
  File "/Users/creator/Documents/TONQuests/TONQuest/server/apps/account/service.py", line 57, in <listcomp>
    return [AccountSchema(**item) for item in result[:limit]]
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for AccountSchema
is_trackable
  Field required [type=missing, input_value={'_id': '672f86cbcb7bcec7...e': 10}, 'out_msgs': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
 - - [core/middlewares.py:96]
[2024-11-19 00:07:11,215] - [   ERROR] - [   root] - [XzouquZwKCtD484LE0AbUg] - GET /account?limit=100 500 Internal Server Error - - [core/middlewares.py:118]
[2024-11-19 00:07:45,783] - [    INFO] - [uvicorn.error] - [e2c1c1a6-b25e-4434-b771-c2f2192bdde9] - Shutting down - - [uvicorn/server.py:262]
[2024-11-19 00:07:45,891] - [    INFO] - [uvicorn.error] - [e2c1c1a6-b25e-4434-b771-c2f2192bdde9] - Waiting for application shutdown. - - [lifespan/on.py:67]
[2024-11-19 00:07:45,894] - [    INFO] - [uvicorn.error] - [e2c1c1a6-b25e-4434-b771-c2f2192bdde9] - Application shutdown complete. - - [lifespan/on.py:76]
[2024-11-19 00:07:45,895] - [    INFO] - [uvicorn.error] - [e2c1c1a6-b25e-4434-b771-c2f2192bdde9] - Finished server process [65418] - - [uvicorn/server.py:92]
[2024-11-19 00:07:46,614] - [    INFO] - [uvicorn.error] - [572ef6d4-dce9-47d8-b6f3-6ed4a231a801] - Started server process [65478] - - [uvicorn/server.py:82]
[2024-11-19 00:07:46,614] - [    INFO] - [uvicorn.error] - [572ef6d4-dce9-47d8-b6f3-6ed4a231a801] - Waiting for application startup. - - [lifespan/on.py:48]
[2024-11-19 00:07:46,616] - [    INFO] - [uvicorn.error] - [572ef6d4-dce9-47d8-b6f3-6ed4a231a801] - Application startup complete. - - [lifespan/on.py:62]
[2024-11-19 00:07:47,744] - [   DEBUG] - [   root] - [fHZkKYWJCMImxmNT1OPcsA] - /account request query: {"limit": "100"} - - [core/middlewares.py:160]
[2024-11-19 00:07:48,048] - [    INFO] - [   root] - [fHZkKYWJCMImxmNT1OPcsA] - GET /account?limit=100 200 OK - - [core/middlewares.py:118]
[2024-11-19 00:07:52,623] - [    INFO] - [uvicorn.error] - [572ef6d4-dce9-47d8-b6f3-6ed4a231a801] - Shutting down - - [uvicorn/server.py:262]
[2024-11-19 00:07:52,727] - [    INFO] - [uvicorn.error] - [572ef6d4-dce9-47d8-b6f3-6ed4a231a801] - Waiting for application shutdown. - - [lifespan/on.py:67]
[2024-11-19 00:07:52,728] - [    INFO] - [uvicorn.error] - [572ef6d4-dce9-47d8-b6f3-6ed4a231a801] - Application shutdown complete. - - [lifespan/on.py:76]
[2024-11-19 00:07:52,728] - [    INFO] - [uvicorn.error] - [572ef6d4-dce9-47d8-b6f3-6ed4a231a801] - Finished server process [65478] - - [uvicorn/server.py:92]
[2024-11-19 00:40:19,253] - [    INFO] - [uvicorn.error] - [50e6780e-17ed-481c-ad45-1ba1508a4569] - Started server process [67670] - - [uvicorn/server.py:82]
[2024-11-19 00:40:19,253] - [    INFO] - [uvicorn.error] - [50e6780e-17ed-481c-ad45-1ba1508a4569] - Waiting for application startup. - - [lifespan/on.py:48]
[2024-11-19 00:40:19,255] - [    INFO] - [uvicorn.error] - [50e6780e-17ed-481c-ad45-1ba1508a4569] - Application startup complete. - - [lifespan/on.py:62]
[2024-11-19 00:42:32,114] - [    INFO] - [uvicorn.error] - [50e6780e-17ed-481c-ad45-1ba1508a4569] - Shutting down - - [uvicorn/server.py:262]
[2024-11-19 00:42:32,223] - [    INFO] - [uvicorn.error] - [50e6780e-17ed-481c-ad45-1ba1508a4569] - Waiting for application shutdown. - - [lifespan/on.py:67]
[2024-11-19 00:42:32,224] - [    INFO] - [uvicorn.error] - [50e6780e-17ed-481c-ad45-1ba1508a4569] - Application shutdown complete. - - [lifespan/on.py:76]
[2024-11-19 00:42:32,224] - [    INFO] - [uvicorn.error] - [50e6780e-17ed-481c-ad45-1ba1508a4569] - Finished server process [67670] - - [uvicorn/server.py:92]
[2024-11-19 00:42:33,164] - [    INFO] - [uvicorn.error] - [df2e7702-cb1d-4f1a-b3b3-71a1447cba13] - Started server process [67755] - - [uvicorn/server.py:82]
[2024-11-19 00:42:33,164] - [    INFO] - [uvicorn.error] - [df2e7702-cb1d-4f1a-b3b3-71a1447cba13] - Waiting for application startup. - - [lifespan/on.py:48]
[2024-11-19 00:42:33,166] - [    INFO] - [uvicorn.error] - [df2e7702-cb1d-4f1a-b3b3-71a1447cba13] - Application startup complete. - - [lifespan/on.py:62]
[2024-11-19 00:45:45,906] - [    INFO] - [uvicorn.error] - [df2e7702-cb1d-4f1a-b3b3-71a1447cba13] - Shutting down - - [uvicorn/server.py:262]
[2024-11-19 00:45:46,010] - [    INFO] - [uvicorn.error] - [df2e7702-cb1d-4f1a-b3b3-71a1447cba13] - Waiting for application shutdown. - - [lifespan/on.py:67]
[2024-11-19 00:45:46,010] - [    INFO] - [uvicorn.error] - [df2e7702-cb1d-4f1a-b3b3-71a1447cba13] - Application shutdown complete. - - [lifespan/on.py:76]
[2024-11-19 00:45:46,010] - [    INFO] - [uvicorn.error] - [df2e7702-cb1d-4f1a-b3b3-71a1447cba13] - Finished server process [67755] - - [uvicorn/server.py:92]
[2024-11-19 00:45:49,035] - [    INFO] - [uvicorn.error] - [ff45e225-1c70-4218-a25d-6466d394312c] - Started server process [67875] - - [uvicorn/server.py:82]
[2024-11-19 00:45:49,035] - [    INFO] - [uvicorn.error] - [ff45e225-1c70-4218-a25d-6466d394312c] - Waiting for application startup. - - [lifespan/on.py:48]
[2024-11-19 00:45:49,037] - [    INFO] - [uvicorn.error] - [ff45e225-1c70-4218-a25d-6466d394312c] - Application startup complete. - - [lifespan/on.py:62]
[2024-11-19 00:45:53,083] - [    INFO] - [uvicorn.error] - [ff45e225-1c70-4218-a25d-6466d394312c] - Shutting down - - [uvicorn/server.py:262]
[2024-11-19 00:45:53,186] - [    INFO] - [uvicorn.error] - [ff45e225-1c70-4218-a25d-6466d394312c] - Waiting for application shutdown. - - [lifespan/on.py:67]
[2024-11-19 00:45:53,187] - [    INFO] - [uvicorn.error] - [ff45e225-1c70-4218-a25d-6466d394312c] - Application shutdown complete. - - [lifespan/on.py:76]
[2024-11-19 00:45:53,187] - [    INFO] - [uvicorn.error] - [ff45e225-1c70-4218-a25d-6466d394312c] - Finished server process [67875] - - [uvicorn/server.py:92]
