[2024-11-18 23:58:30,292] - [    INFO] - [   root] - [HobC_ZNL6D4IrtSTHf4rKg] - GET / 200 OK - - [core/middlewares.py:118]
[2024-11-18 23:58:31,057] - [ WARNING] - [   root] - [kRH-Ai60B5lhwF_d_H3RSw] - GET /favicon.ico 404 Not Found - - [core/middlewares.py:118]
[2024-11-18 23:58:33,587] - [    INFO] - [   root] - [8EgcUzrhxwp2o7-P2TYTNA] - GET /docs 200 OK - - [core/middlewares.py:118]
[2024-11-18 23:58:34,145] - [    INFO] - [   root] - [CduX3zSqumIxECMvWG-1TA] - GET /openapi.json 200 OK - - [core/middlewares.py:118]
[2024-11-19 00:00:19,183] - [    INFO] - [   root] - [V3BkAwoPix7W38Ldg2Ymxg] - GET /docs 200 OK - - [core/middlewares.py:118]
[2024-11-19 00:00:20,060] - [    INFO] - [   root] - [fgcuczWwjdErBmiNknOFWA] - GET /openapi.json 200 OK - - [core/middlewares.py:118]
[2024-11-19 00:00:30,283] - [   ERROR] - [   root] - [rKvLAiSbhx7aA-59fMkRIA] - Error in middleware: 'Provide' object has no attribute 'get_accounts'. Full traceback: Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 111, in receive
    return self.receive_nowait()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 124, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 157, in call_next
    message = await recv_stream.receive()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Documents/TONQuests/TONQuest/server/core/middlewares.py", line 49, in catch_exceptions_middleware
    return await call_next(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/dependency_injector/wiring.py", line 994, in _patched
    return await _async_inject(
  File "src/dependency_injector/_cwiring.pyx", line 66, in _async_inject
  File "/Users/creator/Documents/TONQuests/TONQuest/server/apps/account/router.py", line 29, in get_accounts
    return await account_service.get_accounts(limit)
AttributeError: 'Provide' object has no attribute 'get_accounts'
 - - [core/middlewares.py:96]
[2024-11-19 00:00:30,295] - [   ERROR] - [   root] - [rKvLAiSbhx7aA-59fMkRIA] - GET /account?limit=100 500 Internal Server Error - - [core/middlewares.py:118]
[2024-11-19 00:00:55,844] - [   ERROR] - [   root] - [LPiT3t1IN9znHqVXl1P_Fg] - Error in middleware: 'Provide' object has no attribute 'get_accounts'. Full traceback: Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 111, in receive
    return self.receive_nowait()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 124, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 157, in call_next
    message = await recv_stream.receive()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Documents/TONQuests/TONQuest/server/core/middlewares.py", line 49, in catch_exceptions_middleware
    return await call_next(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/dependency_injector/wiring.py", line 994, in _patched
    return await _async_inject(
  File "src/dependency_injector/_cwiring.pyx", line 66, in _async_inject
  File "/Users/creator/Documents/TONQuests/TONQuest/server/apps/account/router.py", line 29, in get_accounts
    return await account_service.get_accounts(limit)
AttributeError: 'Provide' object has no attribute 'get_accounts'
 - - [core/middlewares.py:96]
[2024-11-19 00:00:55,848] - [   ERROR] - [   root] - [LPiT3t1IN9znHqVXl1P_Fg] - GET /account?limit=100 500 Internal Server Error - - [core/middlewares.py:118]
[2024-11-19 00:03:45,909] - [   ERROR] - [   root] - [sZ0iUWux_8I0JCigpEcnOQ] - Error in middleware: 'Provide' object has no attribute 'get_accounts'. Full traceback: Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 111, in receive
    return self.receive_nowait()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 124, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 157, in call_next
    message = await recv_stream.receive()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Documents/TONQuests/TONQuest/server/core/middlewares.py", line 49, in catch_exceptions_middleware
    return await call_next(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/dependency_injector/wiring.py", line 994, in _patched
    return await _async_inject(
  File "src/dependency_injector/_cwiring.pyx", line 66, in _async_inject
  File "/Users/creator/Documents/TONQuests/TONQuest/server/apps/account/router.py", line 29, in get_accounts
    return await account_service.get_accounts(limit)
AttributeError: 'Provide' object has no attribute 'get_accounts'
 - - [core/middlewares.py:96]
[2024-11-19 00:03:45,911] - [   ERROR] - [   root] - [sZ0iUWux_8I0JCigpEcnOQ] - GET /account?limit=100 500 Internal Server Error - - [core/middlewares.py:118]
[2024-11-19 00:04:34,188] - [   ERROR] - [   root] - [zU1yGU0Xb782uHWfGVbuZg] - Error in middleware: 'Provide' object has no attribute 'get_accounts'. Full traceback: Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 111, in receive
    return self.receive_nowait()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 124, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 157, in call_next
    message = await recv_stream.receive()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Documents/TONQuests/TONQuest/server/core/middlewares.py", line 49, in catch_exceptions_middleware
    return await call_next(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/dependency_injector/wiring.py", line 994, in _patched
    return await _async_inject(
  File "src/dependency_injector/_cwiring.pyx", line 66, in _async_inject
  File "/Users/creator/Documents/TONQuests/TONQuest/server/apps/account/router.py", line 30, in get_accounts
    return await account_service.get_accounts(limit)
AttributeError: 'Provide' object has no attribute 'get_accounts'
 - - [core/middlewares.py:96]
[2024-11-19 00:04:34,197] - [   ERROR] - [   root] - [zU1yGU0Xb782uHWfGVbuZg] - GET /account?limit=100 500 Internal Server Error - - [core/middlewares.py:118]
[2024-11-19 00:06:21,225] - [   ERROR] - [   root] - [aPUX8CbHh8F4iKcE_iqCmQ] - Error in middleware: 'Provide' object has no attribute 'get_accounts'. Full traceback: Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 111, in receive
    return self.receive_nowait()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 124, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 157, in call_next
    message = await recv_stream.receive()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Documents/TONQuests/TONQuest/server/core/middlewares.py", line 49, in catch_exceptions_middleware
    return await call_next(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/dependency_injector/wiring.py", line 994, in _patched
    return await _async_inject(
  File "src/dependency_injector/_cwiring.pyx", line 66, in _async_inject
  File "/Users/creator/Documents/TONQuests/TONQuest/server/apps/account/router.py", line 29, in get_accounts
    return await account_service.get_accounts(limit)
AttributeError: 'Provide' object has no attribute 'get_accounts'
 - - [core/middlewares.py:96]
[2024-11-19 00:06:21,238] - [   ERROR] - [   root] - [aPUX8CbHh8F4iKcE_iqCmQ] - GET /account?limit=100 500 Internal Server Error - - [core/middlewares.py:118]
[2024-11-19 00:07:11,213] - [   ERROR] - [   root] - [XzouquZwKCtD484LE0AbUg] - Error in middleware: 1 validation error for AccountSchema
is_trackable
  Field required [type=missing, input_value={'_id': '672f86cbcb7bcec7...e': 10}, 'out_msgs': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing. Full traceback: Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 111, in receive
    return self.receive_nowait()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 124, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 157, in call_next
    message = await recv_stream.receive()
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creator/Documents/TONQuests/TONQuest/server/core/middlewares.py", line 49, in catch_exceptions_middleware
    return await call_next(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/dependency_injector/wiring.py", line 994, in _patched
    return await _async_inject(
  File "src/dependency_injector/_cwiring.pyx", line 66, in _async_inject
  File "/Users/creator/Documents/TONQuests/TONQuest/server/apps/account/router.py", line 29, in get_accounts
    return await account_service.get_accounts(limit)
  File "/Users/creator/Documents/TONQuests/TONQuest/server/apps/account/service.py", line 57, in get_accounts
    return [AccountSchema(**item) for item in result[:limit]]
  File "/Users/creator/Documents/TONQuests/TONQuest/server/apps/account/service.py", line 57, in <listcomp>
    return [AccountSchema(**item) for item in result[:limit]]
  File "/Users/creator/Library/Caches/pypoetry/virtualenvs/tonquest-rEAuzLtX-py3.10/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for AccountSchema
is_trackable
  Field required [type=missing, input_value={'_id': '672f86cbcb7bcec7...e': 10}, 'out_msgs': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
 - - [core/middlewares.py:96]
[2024-11-19 00:07:11,215] - [   ERROR] - [   root] - [XzouquZwKCtD484LE0AbUg] - GET /account?limit=100 500 Internal Server Error - - [core/middlewares.py:118]
[2024-11-19 00:07:48,048] - [    INFO] - [   root] - [fHZkKYWJCMImxmNT1OPcsA] - GET /account?limit=100 200 OK - - [core/middlewares.py:118]
